awk:
	java -cp javacc.jar javacc awk.jj
	javac -cp .:javacc.jar *.java

run:
	java AWK

nawk:
	java -cp javacc.jar javacc nawk.jj
        javac -cp .:javacc.jar *.java

nrun: 
	java NAWK

wawk:
	java -cp javacc.jar javacc wawk.jj
	javac -cp .:javacc.jar *.java

wrun:
	java WAWK
