nawk:
	java -cp javacc.jar javacc nawk.jj
    javac -cp .:javacc.jar *.java

nrun: 
	java NAWK

wawk:
	java -cp javacc.jar javacc wawk.jj
	javac -cp .:javacc.jar *.java

wrun:
	java WAWK


lexico:
	java -cp javacc.jar javacc Lexico.jj
    javac -cp .:javacc.jar *.java

lrun: 
	java LEXICO
